### ISSUE TITLE
导入微信账单失败

### ISSUE THREAD

**Issue by smallcoderhujin** [dingdangdog/cashbook#33]
![image](https://github.com/dingdangdog/cashbook-desktop/assets/4199380/d34a783b-8e4d-4ddd-9648-af1fe9b6f623)

csv文件没有做任何修改，直接导入报错了

**Comment by dingdangdog** [comment]
首先感谢反馈。

但是，我测试了一下，没有发现问题，能否提供更多错误信息？即使没有选择账本的情况下也成功导入了（虽然未选择账本就能导入数据应该是一个BUG……）

限免是我测试的流程：
1. 通过以下`docker-compose.yml`启动服务：
```yaml
version: "3"

# 单独编排cashbook容器
services:
  cashbook:
    image: dingdangdog/cashbook:1.1.7
    #restart: always
    ports:
      - 880:80
    #volumes:
    #  - ./data:/app/resources/app/data
```
2. 随便注册一个账号；
3. 登录后随便创建一个账本；
4. 1-选择账本后，导入支付宝、微信、京东金融的`csv`文件，成功；
4. 2-不选择账本，导入支付宝、微信、京东金融的`csv`文件，成功；
